server:
  port: 23303

niushuai233:
  zua:
    requestUrl: http://zua-enroll.cpdaily.com/cr-admission/crAdmissionData/queryLqResult
    idcardNumber: xxxxx
    examNumber: xxxxx
    agentid: xxxxx
    cropid: xxxxx
    secret: xxxxx
