server:
  port: 23303

custom-env:
  requestUrl: http://zua-enroll.cpdaily.com/cr-admission/crAdmissionData/queryLqResult
  idcardNumber: xxxxx
  examNumber: xxxxx
  agentid: xxxxx
  cropid: xxxxx
  secret: xxxxx
